export enum Feature {
  AMM = 'AMM',
  NFT = 'NFT',
  BRIDGE = 'Bridge',
  DEFARM = 'DeFarm',
  SWAP = 'Exchange',
  SEANCE = 'Seance',
  VAULT = 'AutoStake Vault',
  AMM_V2 = 'AMM V2',
  EXPLORE = 'Explore',
  LIQUIDITY = 'Liquidity',
  LIQUIDITY_MINING = 'Liquidity Mining',
  BONDS = 'Bonds',
  COFFINBOX = 'CoffinBox',
  UNDERWORLD = 'Underworld',
  MISO = 'MISO',
  ANALYTICS = 'Analytics',
  MIGRATE = 'Migrate',
  STAKING = 'Staking',
  TRIDENT = 'Trident',
  LIMIT_ORDERS = 'LimitOrders',
  LIMIT = 'Limit',
  SOULSWAP = 'SoulSwap',
  LUXOR = 'Luxor',
  INARI = 'Inari',
  AGGREGATE = 'Aggregate',
  VESTING = 'Vesting'
}